# Generated by Django 4.0.3 on 2022-03-17 04:34

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_long_distance_lon'),
    ]

    operations = [
        migrations.AddField(
            model_name='distance',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=32140),
        ),
    ]
