# Generated by Django 4.0.3 on 2022-03-17 05:38

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_distance_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distance',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
